"""生成 dnsdist 规则 Lua (/etc/dnsdist/pdg-generated.lua)。

行为:
  spoof  域名 → A 应答 JP 唯一内网 IP; AAAA → NODATA; HTTPS/SVCB → 空 NOERROR
  block  域名 → NXDOMAIN
  direct 域名 → 不处理, 落到默认 pool 上游递归 (返回真实 IP)

由主 dnsdist.conf 末尾 `dofile("/etc/dnsdist/pdg-generated.lua")` 引入。
目标: dnsdist 1.8+。生成后用 `dnsdist --check-config -C /etc/dnsdist/dnsdist.conf` 校验。
"""

from __future__ import annotations

from datetime import datetime, timezone

from ..model import Config
from ..rules.compiler import CompiledTable


def _lua_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _suffix_node(var: str, names: list[str]) -> list[str]:
    lines = [f"local {var} = newSuffixMatchNode()"]
    for n in names:
        lines.append(f"{var}:add({_lua_str(n)})")
    return lines


def _keyword_regex(keywords: list[str], regexes: list[str]) -> str | None:
    """把 keyword(子串) 与 regex 合成一个 dnsdist 正则 (alternation)。"""
    import re as _re
    parts = [_re.escape(k) for k in keywords] + list(regexes)
    return "|".join(parts) if parts else None


def generate(table: CompiledTable, config: Config) -> str:
    modes = table.matchers_by_dns_mode()
    out: list[str] = []
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")

    out += [
        "-- AUTO-GENERATED by pdg — DO NOT EDIT.",
        f"-- generated: {ts}",
        "-- 源: /etc/pdg/rules.conf (+ policies.conf)。改规则请编辑源文件后 `pdg reload`。",
        "-- 引入: 在主 dnsdist.conf 末尾添加 dofile(\"/etc/dnsdist/pdg-generated.lua\")",
        "",
        f"local SPOOF_IP = {_lua_str(config.jp_internal_ip)}",
        f"local TTL = {config.spoof_ttl}",
        "",
    ]

    # ===== BLOCK (最高优先级) =====
    block = modes["block"]
    block_suffixes = block["domain"] + block["domain_suffix"]
    if block_suffixes:
        out.append("-- ===== BLOCK → NXDOMAIN =====")
        out += _suffix_node("pdgBlock", block_suffixes)
        out.append("addAction(SuffixMatchNodeRule(pdgBlock), RCodeAction(DNSRCode.NXDOMAIN))")
        out.append("")
    block_kr = _keyword_regex(block["domain_keyword"], block["domain_regex"])
    if block_kr:
        out.append(f"addAction(RegexRule({_lua_str(block_kr)}), RCodeAction(DNSRCode.NXDOMAIN))")
        out.append("")

    # ===== PROXY (spoof) =====
    spoof = modes["spoof"]
    spoof_suffixes = spoof["domain"] + spoof["domain_suffix"]
    if spoof_suffixes:
        out.append("-- ===== PROXY → A 应答 JP 内网 IP =====")
        out += _suffix_node("pdgProxy", spoof_suffixes)
        if config.proxy_block_https:
            out.append("-- HTTPS/SVCB 返回空 NOERROR (禁 ECH/HTTP3 协商), 必须排在 spoof 之前")
            out.append("addAction(AndRule({SuffixMatchNodeRule(pdgProxy), "
                       "QTypeRule(DNSQType.HTTPS)}), RCodeAction(DNSRCode.NOERROR))")
        if config.proxy_block_aaaa:
            # SpoofAction 只给 IPv4 → A 命中 JP IP, AAAA 自动 NODATA
            out.append("addAction(SuffixMatchNodeRule(pdgProxy), "
                       "SpoofAction({SPOOF_IP}, {ttl=TTL}))")
        else:
            # 不屏蔽 AAAA: 仅 spoof A, AAAA 落上游 (真实 IPv6)
            out.append("addAction(AndRule({SuffixMatchNodeRule(pdgProxy), "
                       "QTypeRule(DNSQType.A)}), SpoofAction({SPOOF_IP}, {ttl=TTL}))")
        out.append("")

    spoof_kr = _keyword_regex(spoof["domain_keyword"], spoof["domain_regex"])
    if spoof_kr:
        out.append("-- PROXY (keyword/regex)")
        if config.proxy_block_https:
            out.append(f"addAction(AndRule({{RegexRule({_lua_str(spoof_kr)}), "
                       "QTypeRule(DNSQType.HTTPS)}), RCodeAction(DNSRCode.NOERROR))")
        if config.proxy_block_aaaa:
            out.append(f"addAction(RegexRule({_lua_str(spoof_kr)}), "
                       "SpoofAction({SPOOF_IP}, {ttl=TTL}))")
        else:
            out.append(f"addAction(AndRule({{RegexRule({_lua_str(spoof_kr)}), "
                       "QTypeRule(DNSQType.A)}), SpoofAction({SPOOF_IP}, {ttl=TTL}))")
        out.append("")

    out.append("-- DIRECT 及其余域名: 落默认 pool 上游递归 (主 dnsdist.conf 中 newServer 定义), 返回真实 IP")
    out.append("")
    return "\n".join(out)
