"""生成 nftables TPROXY 脚本, 把发往 JP 内网 IP 的 80/443 交给 sing-box。

TPROXY 还需要策略路由 (mark → lo 本地表), 见脚本头部注释与 docs/deployment.md。
V1 仅 TCP。
"""

from __future__ import annotations

from ..model import Config

FWMARK = "0x1"
ROUTE_TABLE = "100"


def generate(config: Config) -> str:
    ip = config.jp_internal_ip
    port = config.tproxy_port
    return f"""#!/usr/sbin/nft -f
# AUTO-GENERATED by pdg — DO NOT EDIT. 源: /etc/pdg/pdg.conf
#
# 依赖策略路由 (放到 systemd 或 /etc/networkd-dispatcher, 仅需设置一次):
#   ip rule add fwmark {FWMARK} lookup {ROUTE_TABLE}
#   ip route add local 0.0.0.0/0 dev lo table {ROUTE_TABLE}
#   ip -6 rule add fwmark {FWMARK} lookup {ROUTE_TABLE}
#   ip -6 route add local ::/0 dev lo table {ROUTE_TABLE}
#
# 应用: nft -f /var/lib/pdg/out/pdg.nft (或安装到 /etc/nftables.d/)

# 原子替换惯用法: 先确保空表存在, 再删除, 再重建。
table inet pdg {{}}
delete table inet pdg

table inet pdg {{
    chain prerouting {{
        type filter hook prerouting priority mangle; policy accept;

        # 仅接管【发往 JP 唯一内网 IP】的 TCP 80/443, 交给 sing-box tproxy 入口。
        ip  daddr {ip} tcp dport {{ {config.http_port}, {config.https_port} }} \\
            tproxy to :{port} meta mark set {FWMARK} accept

        # 其余流量不动。
    }}
}}
"""
